#application
spring.application.name=demoBank
spring.profiles.active=jpa

# server configuration
server.port=8081

# persistence
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=watashi
spring.datasource.password=devpass

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Actuator & Prometheus Metrics Exposure
management.endpoints.web.exposure.include=*
management.endpoint.prometheus.enabled=true